import axios from 'axios'
import { useEffect,useState,type FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { formApi,type FieldType,type FormDefinition,type FormField,type FormSection,type FormSummary } from './formApi'

const fieldTypes:FieldType[]=['TEXT','TEXTAREA','INTEGER','DECIMAL','DATE','BOOLEAN','SELECT','MULTI_SELECT','RADIO','CHECKBOX','EMAIL','PHONE','FILE']
const optionTypes=new Set<FieldType>(['SELECT','MULTI_SELECT','RADIO'])
const emptyField=():FormField=>({key:'',label:'',type:'TEXT',required:false,placeholder:null,validationRules:{},options:[]})
const emptySection=():FormSection=>({title:'Yeni bölüm',description:null,fields:[emptyField()]})

export function FormBuilderPage(){
 const {periodId=''}=useParams();const [versions,setVersions]=useState<FormSummary[]>([]);const [form,setForm]=useState<FormDefinition|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('')
 useEffect(()=>{let active=true;formApi.list(periodId).then(async values=>({values,selected:values[0]?await formApi.get(values[0].id):null})).then(({values,selected})=>{if(active){setVersions(values);setForm(selected);setLoading(false)}}).catch(error=>{if(active){setError(message(error));setLoading(false)}});return()=>{active=false}},[periodId])
 async function choose(id:string){setError('');try{setForm(await formApi.get(id))}catch(e){setError(message(e))}}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{const created=await formApi.create(periodId,String(data.get('name')));setForm(created);setVersions(await formApi.list(periodId))}catch(e){setError(message(e))}}
 function updateSection(index:number,change:Partial<FormSection>){if(!form)return;setForm({...form,sections:form.sections.map((section,i)=>i===index?{...section,...change}:section)})}
 function updateField(sectionIndex:number,fieldIndex:number,change:Partial<FormField>){if(!form)return;const sections=form.sections.map((section,i)=>i===sectionIndex?{...section,fields:section.fields.map((field,j)=>j===fieldIndex?{...field,...change}:field)}:section);setForm({...form,sections})}
 function removeSection(index:number){if(form)setForm({...form,sections:form.sections.filter((_,i)=>i!==index)})}
 function removeField(sectionIndex:number,fieldIndex:number){if(!form)return;setForm({...form,sections:form.sections.map((section,i)=>i===sectionIndex?{...section,fields:section.fields.filter((_,j)=>j!==fieldIndex)}:section)})}
 function moveField(sectionIndex:number,fieldIndex:number,direction:number){if(!form)return;const fields=[...form.sections[sectionIndex].fields];const next=fieldIndex+direction;if(next<0||next>=fields.length)return;[fields[fieldIndex],fields[next]]=[fields[next],fields[fieldIndex]];updateSection(sectionIndex,{fields})}
 function updateRule(sectionIndex:number,fieldIndex:number,key:string,value:string){if(!form)return;const field=form.sections[sectionIndex].fields[fieldIndex];const rules={...field.validationRules};if(value==='')delete rules[key];else rules[key]=key==='pattern'?value:Number(value);updateField(sectionIndex,fieldIndex,{validationRules:rules})}
 function moveSection(index:number,direction:number){if(!form)return;const next=index+direction;if(next<0||next>=form.sections.length)return;const sections=[...form.sections];[sections[index],sections[next]]=[sections[next],sections[index]];setForm({...form,sections})}
 async function save(){if(!form)return;setSaving(true);setError('');setNotice('');try{const updated=await formApi.save(form);setForm(updated);setVersions(await formApi.list(periodId));setNotice('Taslak kaydedildi.')}catch(e){setError(message(e))}finally{setSaving(false)}}
 async function publish(){if(!form)return;setSaving(true);try{const updated=await formApi.publish(form);setForm(updated);setVersions(await formApi.list(periodId));setNotice('Form yayınlandı.')}catch(e){setError(message(e))}finally{setSaving(false)}}
 async function newVersion(){if(!form)return;setSaving(true);try{const updated=await formApi.newVersion(form);setForm(updated);setVersions(await formApi.list(periodId));setNotice('Yeni taslak versiyon oluşturuldu.')}catch(e){setError(message(e))}finally{setSaving(false)}}
 if(loading)return <p role="status">Formlar yükleniyor…</p>
 return <section className="admin-workspace form-builder"><header><p className="eyebrow">Dinamik form</p><h1>Başvuru formu builder</h1><p>Bölüm ve alanları yönetin. Yayınlanan sürümler değiştirilemez.</p></header>{error&&<p role="alert" className="status status--error">{error}</p>}{notice&&<p role="status" className="status status--success">{notice}</p>}
  {!form?<form className="management-card form-create" onSubmit={create}><h2>İlk formu oluştur</h2><label>Form adı<input name="name" required maxLength={200} defaultValue="Başvuru Formu"/></label><button>Form oluştur</button></form>:<>
   <div className="builder-toolbar"><label>Versiyon<select aria-label="Form versiyonu" value={form.id} onChange={e=>void choose(e.target.value)}>{versions.map(value=><option key={value.id} value={value.id}>v{value.versionNumber} · {value.status}</option>)}</select></label><span className={`form-badge form-badge--${form.status.toLowerCase()}`}>{form.status}</span>{form.status==='DRAFT'?<><button disabled={saving} onClick={()=>void save()}>Taslağı kaydet</button><button className="secondary" disabled={saving||form.sections.length===0} onClick={()=>void publish()}>Yayınla</button></>:<button disabled={saving||versions.some(value=>value.status==='DRAFT')} onClick={()=>void newVersion()}>Yeni versiyon oluştur</button>}</div>
   {form.status==='DRAFT'?<div className="builder-content"><label>Form adı<input value={form.name} maxLength={200} onChange={e=>setForm({...form,name:e.target.value})}/></label>{form.sections.map((section,sectionIndex)=><section className="builder-section" key={section.id??sectionIndex}><div className="builder-section__heading"><label>Bölüm başlığı<input value={section.title} onChange={e=>updateSection(sectionIndex,{title:e.target.value})}/></label><label>Açıklama<input value={section.description??''} onChange={e=>updateSection(sectionIndex,{description:e.target.value||null})}/></label><div><button aria-label="Bölümü yukarı taşı" className="icon-button" onClick={()=>moveSection(sectionIndex,-1)}>↑</button><button aria-label="Bölümü aşağı taşı" className="icon-button" onClick={()=>moveSection(sectionIndex,1)}>↓</button><button className="danger" onClick={()=>removeSection(sectionIndex)}>Bölümü sil</button></div></div>
    {section.fields.map((field,fieldIndex)=><article className="field-editor" key={field.id??fieldIndex}><label>Alan anahtarı<input value={field.key} pattern="[a-z][a-z0-9_]*" placeholder="family_income" onChange={e=>updateField(sectionIndex,fieldIndex,{key:e.target.value})}/></label><label>Etiket<input value={field.label} onChange={e=>updateField(sectionIndex,fieldIndex,{label:e.target.value})}/></label><label>Tür<select value={field.type} onChange={e=>updateField(sectionIndex,fieldIndex,{type:e.target.value as FieldType,options:optionTypes.has(e.target.value as FieldType)?field.options:[]})}>{fieldTypes.map(type=><option key={type}>{type}</option>)}</select></label><label>Placeholder<input value={field.placeholder??''} onChange={e=>updateField(sectionIndex,fieldIndex,{placeholder:e.target.value||null})}/></label><label className="check-label"><input type="checkbox" checked={field.required} onChange={e=>updateField(sectionIndex,fieldIndex,{required:e.target.checked})}/> Zorunlu</label><div className="field-actions"><button aria-label="Alanı yukarı taşı" onClick={()=>moveField(sectionIndex,fieldIndex,-1)}>↑</button><button aria-label="Alanı aşağı taşı" onClick={()=>moveField(sectionIndex,fieldIndex,1)}>↓</button><button className="danger" onClick={()=>removeField(sectionIndex,fieldIndex)}>Sil</button></div>
     {['TEXT','TEXTAREA','EMAIL','PHONE'].includes(field.type)&&<div className="validation-editor"><label>Min. uzunluk<input type="number" min="0" value={field.validationRules.minLength??''} onChange={e=>updateRule(sectionIndex,fieldIndex,'minLength',e.target.value)}/></label><label>Maks. uzunluk<input type="number" min="0" value={field.validationRules.maxLength??''} onChange={e=>updateRule(sectionIndex,fieldIndex,'maxLength',e.target.value)}/></label><label>Pattern<input value={field.validationRules.pattern??''} onChange={e=>updateRule(sectionIndex,fieldIndex,'pattern',e.target.value)}/></label></div>}
     {['INTEGER','DECIMAL'].includes(field.type)&&<div className="validation-editor"><label>Minimum<input type="number" value={field.validationRules.min??''} onChange={e=>updateRule(sectionIndex,fieldIndex,'min',e.target.value)}/></label><label>Maksimum<input type="number" value={field.validationRules.max??''} onChange={e=>updateRule(sectionIndex,fieldIndex,'max',e.target.value)}/></label></div>}
     {optionTypes.has(field.type)&&<OptionEditor field={field} onChange={options=>updateField(sectionIndex,fieldIndex,{options})}/>}</article>)}<button className="secondary" onClick={()=>updateSection(sectionIndex,{fields:[...section.fields,emptyField()]})}>Alan ekle</button></section>)}<button onClick={()=>setForm({...form,sections:[...form.sections,emptySection()]})}>Bölüm ekle</button></div>:<FormPreview form={form}/>}</>}
 </section>
}

function OptionEditor({field,onChange}:{field:FormField;onChange:(options:FormField['options'])=>void}){function move(index:number,direction:number){const options=[...field.options];const next=index+direction;if(next<0||next>=options.length)return;[options[index],options[next]]=[options[next],options[index]];onChange(options)}return <fieldset className="option-editor"><legend>Seçenekler</legend>{field.options.map((option,index)=><div key={option.id??index}><input aria-label={`Seçenek ${index+1} etiketi`} placeholder="Etiket" value={option.label} onChange={e=>onChange(field.options.map((value,i)=>i===index?{...value,label:e.target.value}:value))}/><input aria-label={`Seçenek ${index+1} değeri`} placeholder="deger" value={option.value} onChange={e=>onChange(field.options.map((value,i)=>i===index?{...value,value:e.target.value}:value))}/><button aria-label={`Seçenek ${index+1} yukarı`} onClick={()=>move(index,-1)}>↑</button><button aria-label={`Seçenek ${index+1} aşağı`} onClick={()=>move(index,1)}>↓</button><button className="danger" onClick={()=>onChange(field.options.filter((_,i)=>i!==index))}>Sil</button></div>)}<button className="secondary" onClick={()=>onChange([...field.options,{label:'',value:''}])}>Seçenek ekle</button></fieldset>}
function FormPreview({form}:{form:FormDefinition}){return <div className="form-preview"><h2>{form.name}</h2>{form.sections.map(section=><section key={section.id}><h3>{section.title}</h3>{section.description&&<p>{section.description}</p>}{section.fields.map(field=><div className="preview-field" key={field.id}><strong>{field.label}{field.required?' *':''}</strong><span>{field.type}{field.options.length?` · ${field.options.map(option=>option.label).join(', ')}`:''}</span></div>)}</section>)}</div>}
function message(error:unknown){return axios.isAxiosError(error)?error.response?.data?.message??'İşlem tamamlanamadı.':'İşlem tamamlanamadı.'}
