import{useCallback,useEffect,useState}from'react';import{Link,useParams}from'react-router-dom';import{publicContentApi,type Faq}from'./publicContentApi';
function useLoad<T>(load:()=>Promise<T>){const[data,setData]=useState<T>();const[error,setError]=useState(false);useEffect(()=>{let active=true;load().then(v=>{if(active)setData(v)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[load]);return{data,error}}
export function HomePage(){return <section className="public-page hero"><p className="eyebrow">Turing Scholarship</p><h1>Potansiyelini geleceğe taşı.</h1><p>Burs programlarını incele, başvuru dönemlerini takip et ve eğitim yolculuğunda yanında olacak desteğe ulaş.</p><div className="public-actions"><Link className="button-link" to="/scholarships">Bursları incele</Link><Link className="button-link secondary" to="/about">Hakkımızda</Link></div></section>}
export function ScholarshipsPage(){const load=useCallback(()=>publicContentApi.scholarships(),[]);const{data,error}=useLoad(load);return <PublicList title="Burs programları" error={error}>{data?.map(v=><article key={v.program.id}><h2>{v.program.name}</h2><p>{v.program.description}</p><p>{v.periods.length} başvuru dönemi</p><Link to={`/scholarships/${v.program.slug}`}>Programı incele</Link></article>)}</PublicList>}
export function ScholarshipDetailPage(){const{slug=''}=useParams();const load=useCallback(()=>publicContentApi.scholarship(slug),[slug]);const{data,error}=useLoad(load);return <PublicList title={data?.program.name??'Burs programı'} error={error}>{data&&<><p>{data.program.description}</p>{data.periods.map(p=><article key={p.id}><h2>{p.name}</h2><p>{p.academicYear} · {p.status}</p><p>{format(p.startsAt)} – {format(p.endsAt)}</p>{p.status==='OPEN'&&<Link to="/login">Başvuru yapmak için giriş yap</Link>}</article>)}</>}</PublicList>}
export function AnnouncementsPage(){const load=useCallback(()=>publicContentApi.announcements(),[]);const{data,error}=useLoad(load);return <PublicList title="Duyurular" error={error}>{data?.map(v=><article key={v.id}><time>{v.publishedAt&&format(v.publishedAt)}</time><h2>{v.title}</h2><p>{v.summary}</p><Link to={`/announcements/${v.slug}`}>Devamını oku</Link></article>)}</PublicList>}
export function AnnouncementDetailPage(){const{slug=''}=useParams();const load=useCallback(()=>publicContentApi.announcement(slug),[slug]);const{data,error}=useLoad(load);return <PublicList title={data?.title??'Duyuru'} error={error}>{data&&<article><time>{data.publishedAt&&format(data.publishedAt)}</time><p className="content-text">{data.content}</p></article>}</PublicList>}
export function FaqPage(){const load=useCallback(()=>publicContentApi.faqs(),[]);const{data,error}=useLoad(load);return <PublicList title="Sıkça sorulan sorular" error={error}>{data?.map((v:Faq)=><details key={v.id}><summary>{v.question}</summary><p>{v.answer}</p></details>)}</PublicList>}
export function AboutPage(){return <PublicList title="Hakkımızda"><p>Turing Scholarship, öğrencilerin eğitim yolculuklarını şeffaf ve erişilebilir burs süreçleriyle desteklemek için çalışır.</p></PublicList>}
export function ContactPage(){return <PublicList title="İletişim"><p>Burs süreçleriyle ilgili sorularınız için <a href="mailto:info@turing.local">info@turing.local</a> adresinden bize ulaşabilirsiniz.</p></PublicList>}
function PublicList({title,error=false,children}:{title:string;error?:boolean;children:React.ReactNode}){return <section className="public-page"><p className="eyebrow">Turing Scholarship</p><h1>{title}</h1>{error?<p role="alert">İçerik yüklenemedi.</p>:<div className="public-list">{children}</div>}</section>};function format(v:string){return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(new Date(v))}
